---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v2.7.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: hashicorp/terraform@v1.1.9
